import "SettingsViewModel.idl";

namespace WinUI_Mvvm
{
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
        
        SettingsViewModel ViewModel{ get; };
    }
}
